# Generated by Django 5.2.17 on 2026-08-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryalbum_deleted_at_galleryalbum_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'ordering': ['-created'], 'verbose_name': 'آلبوم گالری', 'verbose_name_plural': 'آلبوم\u200cهای گالری'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان تصویر'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان آلبوم'),
        ),
    ]
