# Generated by Django 5.2.17 on 2026-08-19 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='دسته مادر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.TextField(blank=True, verbose_name='چکیده')),
                ('content', models.TextField(verbose_name='توضیحات / متن مقاله')),
                ('featured_image', models.ImageField(upload_to='blog/%Y/%m/', verbose_name='تصویر شاخص')),
                ('read_time', models.PositiveIntegerField(default=1, verbose_name='زمان تقریبی خواندن (دقیقه)')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='لایک\u200cها')),
                ('published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish_date', '-created'],
            },
        ),
    ]
