# Generated by Django 5.2.17 on 2026-08-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_deleted_at_post_is_deleted_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدیدها'),
        ),
    ]
