# Generated by Django 5.2.17 on 2026-08-24 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='شناسه سشن')),
                ('target_type', models.CharField(choices=[('post', 'مقاله'), ('comment', 'کامنت')], max_length=10, verbose_name='نوع')),
                ('target_id', models.PositiveIntegerField(verbose_name='شناسه هدف')),
                ('vote_type', models.CharField(choices=[('like', 'لایک'), ('dislike', 'دیسلایک')], max_length=10, verbose_name='نوع رأی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_votes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رکورد رأی',
                'verbose_name_plural': 'رکوردهای رأی',
                'unique_together': {('ip_address', 'target_type', 'target_id'), ('session_key', 'target_type', 'target_id'), ('user', 'target_type', 'target_id')},
            },
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
