# Generated by Django 5.2.17 on 2026-08-31 07:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_voterecord_delete_commentvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='متن مقاله'),
        ),
    ]
