# Generated by Django 5.2.17 on 2026-08-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='زاسکو ذوب', help_text='در هر صفحه جلوی آن می\u200cآید؛ مثل «زاسکو ذوب - درباره ما»', max_length=100, verbose_name='عنوان اصلی سایت')),
                ('phone_mobile', models.CharField(max_length=20, verbose_name='شماره موبایل شرکت')),
                ('phone_office', models.CharField(max_length=20, verbose_name='شماره تلفن ثابت شرکت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل شرکت')),
                ('address_factory', models.TextField(verbose_name='آدرس کارخانه')),
                ('address_rd', models.TextField(verbose_name='آدرس واحد تحقیقات و فناوری')),
                ('link_whatsapp', models.URLField(blank=True, verbose_name='لینک واتساپ')),
                ('link_instagram', models.URLField(blank=True, verbose_name='لینک اینستاگرام')),
                ('link_eitaa', models.URLField(blank=True, verbose_name='لینک ایتا')),
                ('footer_title', models.CharField(max_length=150, verbose_name='عنوان فوتر')),
                ('footer_description', models.TextField(verbose_name='توضیحات زیر عنوان فوتر')),
                ('newsletter_text', models.CharField(default='با عضویت در خبرنامه سریع\u200cتر در جریان اخبار قرار بگیرید', max_length=200, verbose_name='متن خبرنامه')),
                ('copyright_text', models.TextField(verbose_name='متن کپی\u200cرایت')),
                ('catalog_qr', models.ImageField(blank=True, upload_to='catalog/', verbose_name='تصویر QR کاتالوگ')),
                ('catalog_link', models.URLField(blank=True, verbose_name='لینک کاتالوگ')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
