# Generated by Django 5.2.17 on 2026-08-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='link_eitaa',
        ),
    ]
