# Generated by Django 5.2.17 on 2026-08-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactmessage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contact_attachments/%Y/%m/', verbose_name='فایل پیوست'),
        ),
    ]
