# Generated by Django 5.2.17 on 2026-08-23 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_body',
            field=models.TextField(blank=True, null=True, verbose_name='متن پاسخ'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع پاسخ'),
        ),
        migrations.CreateModel(
            name='ReplyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reply_attachments/%Y/%m/', verbose_name='فایل پیوست')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_attachments', to='main.contactmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیوست پاسخ',
                'verbose_name_plural': 'پیوست\u200cهای پاسخ',
            },
        ),
    ]
