# Generated by Django 5.2.17 on 2026-08-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactmessage_replied_at_contactmessage_reply_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_title',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_text',
            field=models.TextField(default='کارخانه ریخته\u200cگری زاسکو ذوب فعال در زمینه\u200cهای ریخته\u200cگری آلیاژهای آهنی و غیرآهنی...', verbose_name='متن توضیح کلی شرکت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_title_company',
            field=models.CharField(default='اطلاعات شرکت', max_length=100, verbose_name='سرعنوان: اطلاعات شرکت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_title_newsletter',
            field=models.CharField(default='خبرنامه', max_length=100, verbose_name='سرعنوان: خبرنامه'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_title_pages',
            field=models.CharField(default='دیگر صفحات', max_length=100, verbose_name='سرعنوان: دیگر صفحات'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='link_aparat',
            field=models.URLField(blank=True, verbose_name='لینک آپارات'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='link_linkedin',
            field=models.URLField(blank=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='link_telegram',
            field=models.URLField(blank=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='link_youtube',
            field=models.URLField(blank=True, verbose_name='لینک یوتیوب'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='newsletter_button_text',
            field=models.CharField(default='مشترک شدن', max_length=50, verbose_name='متن دکمه خبرنامه'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='subtitle',
            field=models.CharField(default='قطعه ریزان ذوب آرای سپاهان', help_text='در هدر یا هیرو نمایش داده می\u200cشود', max_length=150, verbose_name='زیرعنوان سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address_factory',
            field=models.TextField(default='اصفهان، نجف\u200cآباد، شهرک صنعتی منتظریه، ابتدای خیابان قادری شمالی، ضلع غربی، پلاک ۲، کد ۱۳۰', verbose_name='آدرس کارخانه'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address_rd',
            field=models.TextField(default='اصفهان، نجف\u200cآباد، دانشگاه آزاد اسلامی، ساختمان علم و فناوری، اتاق ۳۰۲', verbose_name='آدرس واحد تحقیقات و فناوری'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='copyright_text',
            field=models.TextField(default='تمامی منابع، تصاویر، حقوق و مطالب موجود در این وبسایت متعلق به قطعه ریزان ذوب آرای سپاهان است و هرگونه کپی\u200cبرداری از آن پیگرد قانونی دارد © ۱۴۰۵', verbose_name='متن کپی\u200cرایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(default='zascozob@gmail.com', max_length=254, verbose_name='ایمیل شرکت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_description',
            field=models.TextField(blank=True, verbose_name='توضیحات زیر عنوان فوتر (بالای کپی\u200cرایت)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone_mobile',
            field=models.CharField(default='+989134302591', max_length=20, verbose_name='شماره موبایل شرکت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone_office',
            field=models.CharField(default='031-42318530', max_length=20, verbose_name='شماره تلفن ثابت شرکت'),
        ),
    ]
