# Generated by Django 5.2.17 on 2026-08-31 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_sitesetting_footer_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='address_factory',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='address_rd',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='catalog_link',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='catalog_qr',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='copyright_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_description',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_title_company',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_title_newsletter',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_title_pages',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='link_aparat',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='link_instagram',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='link_linkedin',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='link_telegram',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='link_whatsapp',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='link_youtube',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='newsletter_button_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='newsletter_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='phone_mobile',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='phone_office',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='site_title',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_message',
            field=models.TextField(blank=True, default='سایت در حال بروزرسانی است. لطفاً بعداً مراجعه کنید.', verbose_name='پیام حالت تعمیر'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='حالت تعمیر'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='عملیات')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه شیء')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ فعالیت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='media_library/%Y/%m/', verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('image', 'تصویر'), ('document', 'سند'), ('video', 'ویدیو'), ('audio', 'صدا'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع فایل')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم فایل (بایت)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع MIME')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلود کننده')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'کتابخانه فایل\u200cها',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
