# Generated by Django 5.2.17 on 2026-08-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_sitesetting_about_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='mime_type',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین (ALT)'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='used_in',
            field=models.CharField(blank=True, help_text='مثلاً: portfolio, blog, gallery', max_length=100, verbose_name='استفاده شده در'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='حجم فایل (بایت)'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان فایل'),
        ),
    ]
