"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ═══ مدیا (بعد از BASE_DIR) ═══
MEDIA_URL = '/media/'; MEDIA_ROOT = BASE_DIR / 'media'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-27ex-39+r0dsn4(0t))ry8^*wsr+tjj%1uennd_)+&w-f$j7#4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin','django.contrib.auth','django.contrib.contenttypes',
    'django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles',
    'main','gallery','blog','portfolio','panel','django_ckeditor_5',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'main' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.site_settings',
            ],
        },
    },
]
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'main' / 'static',
    BASE_DIR / 'blog' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ═══ Gmail SMTP ═══
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 15
EMAIL_HOST_USER = 'zascozob@gmail.com'
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = 'Zasco Foundry <zascozob@gmail.com>'
CONTACT_EMAIL = 'zascozob@gmail.com'

# ═══ CKEditor 5 ═══
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "authenticated"

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', '|', 'bulletedList', 'numberedList', '|', 'undo', 'redo'],
    },
    'extends': {
        'toolbar': [
            'heading', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'bold', 'italic', 'underline', 'strikethrough', 'subscript', 'superscript', 'code', '|',
            'removeFormat', '|',
            'bulletedList', 'numberedList', 'todoList', '|',
            'outdent', 'indent', 'alignment', '|',
            'link', 'uploadImage', 'insertImage', 'blockQuote', 'insertTable', 'mediaEmbed', 'codeBlock', 'specialCharacters', 'horizontalLine', 'highlight', '|',
            'undo', 'redo', '|',
            'sourceEditing', 'findAndReplace', 'selectAll'
        ],
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'پاراگراف', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'عنوان ۱', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'عنوان ۲', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'عنوان ۳', 'class': 'ck-heading_heading3'},
                {'model': 'heading4', 'view': 'h4', 'title': 'عنوان ۴', 'class': 'ck-heading_heading4'},
            ]
        },
        'fontFamily': {'options': ['default', 'Vazirmatn, sans-serif', 'Tahoma, sans-serif', 'Arial, sans-serif', 'Georgia, serif', 'Courier New, monospace']},
        'fontSize': {'options': ['tiny', 'small', 'default', 'big', 'huge']},
        'fontColor': {
            'colors': [
                {'color': '#eef1f6', 'label': 'سفید'},
                {'color': '#ff6b00', 'label': 'نارنجی'},
                {'color': '#f44336', 'label': 'قرمز'},
                {'color': '#4caf50', 'label': 'سبز'},
                {'color': '#2196f3', 'label': 'آبی'},
                {'color': '#ffc107', 'label': 'زرد'},
                {'color': '#9c27b0', 'label': 'بنفش'},
                {'color': '#000000', 'label': 'مشکی'},
            ],
            'columns': 4
        },
        'fontBackgroundColor': {
            'colors': [
                {'color': 'transparent', 'label': 'بدون رنگ'},
                {'color': '#ff6b00', 'label': 'نارنجی'},
                {'color': '#f44336', 'label': 'قرمز'},
                {'color': '#4caf50', 'label': 'سبز'},
                {'color': '#2196f3', 'label': 'آبی'},
                {'color': '#ffc107', 'label': 'زرد'},
                {'color': '#000000', 'label': 'مشکی'},
                {'color': '#ffffff', 'label': 'سفید'},
            ],
            'columns': 4
        },
        'list': {'properties': {'styles': True, 'startIndex': True, 'reversed': True}},
        'link': {'addTargetToExternalLinks': True, 'defaultProtocol': 'https://'},
        'image': {'toolbar': ['imageTextAlternative', '|', 'imageStyle:inline', 'imageStyle:wrapText', 'imageStyle:breakText', '|', 'resizeImage']},
        'table': {'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells', 'tableCellProperties', 'tableProperties']},
        'codeBlock': {'languages': [
            {'language': 'plaintext', 'label': 'متن ساده'},
            {'language': 'python', 'label': 'Python'},
            {'language': 'javascript', 'label': 'JavaScript'},
            {'language': 'html', 'label': 'HTML'},
            {'language': 'css', 'label': 'CSS'},
        ]},
        'mediaEmbed': {'previewsInData': True},
        'language': 'fa',
    },
}