# Generated by Django 5.2.17 on 2026-08-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='برچسب')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نمونه\u200cکار')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.TextField(blank=True, verbose_name='چکیده')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cover', models.ImageField(upload_to='portfolio/%Y/%m/', verbose_name='تصویر شاخص')),
                ('published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='portfolio.tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'نمونه\u200cکار',
                'verbose_name_plural': 'نمونه\u200cکارها',
                'ordering': ['-created'],
            },
        ),
    ]
