# Generated by Django 5.2.17 on 2026-08-25 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_deleted_at_portfolioitem_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان دسته')),
                ('slug', models.SlugField(allow_unicode=True, max_length=160, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات سئو')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته نمونه\u200cکار',
                'verbose_name_plural': 'دسته\u200cهای نمونه\u200cکار',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='tags',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='cover',
            new_name='featured_image',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='order',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='content',
            field=models.TextField(blank=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین تصویر (سئو)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='جنس آلیاژ'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='standard',
            field=models.CharField(blank=True, max_length=100, verbose_name='استاندارد'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='summary',
            field=models.CharField(blank=True, max_length=300, verbose_name='خلاصه'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدید'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='وزن قطعه'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='published',
            field=models.BooleanField(default=True, verbose_name='منتشر شده'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان قطعه'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='portfolio.portfoliocategory', verbose_name='دسته'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
