# Generated by Django 5.2.17 on 2026-08-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliocategory_remove_portfolioitem_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='content',
            field=models.TextField(blank=True, verbose_name='توضیحات کامل (JSON)'),
        ),
    ]
