# Generated by Django 5.2.17 on 2026-08-27 07:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolioitem_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات کامل'),
        ),
    ]
